site_name: TFx Docs
site_url: https://tfx.rocks
site_author: Tom Straub
site_description: "A standalone CLI for Terraform Cloud and Terraform Enterprise."
repo_url: "https://github.com/straubt1/tfx"
copyright: "TFx is licensed under the <a href='https://github.com/straubt1/tfx/blob/main/LICENSE'>MIT license</a>"

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  # highlightjs: true
  # hljs_languages:
  #   - hcl

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Commands: commands.md